services:
  db:
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${EXPOSE_DATABASE_PORT}:3306"
    volumes:
      - ruby-app-database:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    env_file:
      - .env.local.backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/app
    environment:
      TZ: ${TZ}
      RAILS_ENV: ${RAILS_ENV}
    links:
      - db
    ports:
      - "${EXPOSE_BACKEND_PORT}:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    env_file:
      - .env.local.frontend
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./frontend/src:/app
      - ruby-app-frontend-node-modules:/app/node_modules
      - ruby-app-frontend-next:/app/.next
    ports:
      - "${EXPOSE_FRONTEND_PORT}:3000"
    command: npm run dev
    tty: true

volumes:
  ruby-app-frontend-node-modules:
  ruby-app-frontend-next:
  ruby-app-database:
